# Numpy

In [7]:
!pip install numpy

In [22]:
import numpy as np

In [23]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]) 

In [24]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [12]:
type(array1)

numpy.ndarray

In [13]:
array1.shape

(11,)

In [25]:
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [26]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
array2.shape

(3, 4)

In [28]:
print(array1.size)
array2.size

11


12

In [30]:
array1 = np.full(6, 0)
array1

array([0, 0, 0, 0, 0, 0])

In [32]:
array2 = np.zeros(6)
array2

array([0., 0., 0., 0., 0., 0.])

In [34]:
array3 = np.full(6, 6)
array3

array([6, 6, 6, 6, 6, 6])

In [35]:
array4 = np.ones(6)
array4

array([1., 1., 1., 1., 1., 1.])

## 인덱싱, 슬라이싱

In [36]:
import numpy as np

In [38]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]) 

In [39]:
array1[0]

2

In [41]:
array1[2]

5

In [42]:
array1[-1]

31

In [43]:
array1[-2]

29

In [45]:
array1[[1, 3, 5]]

array([ 3,  7, 13])

In [47]:
array2=np.arange(1,10,2)
array2

array([1, 3, 5, 7, 9])

In [49]:
array1[array2]

array([ 3,  7, 13, 19, 29])

In [50]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [51]:
array1[1:]

array([ 3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [52]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [54]:
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

In [55]:
array1[2:11:3]

array([ 5, 13, 23])

## numpy 기본연산

In [56]:
import numpy as np

In [58]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [59]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

### 같은 행끼리 덧셈 곱셈 뺄셈 나눗셈 알아서 동작한다

In [66]:
print(array1)
print(array2)
array1 + array2

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

``` 신주쿠 흥부부대찌개 ```

In [67]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

won_array = np.array(revenue_in_yen) * 10.08

# 정답 출력
won_array

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

## numpy boolean 연산

In [68]:
import numpy as np
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]) 

In [70]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [73]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [75]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True])

where => True 값을 가진 인덱스만 출력

In [76]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [81]:
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [82]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

## numpy 기본 통계
```
최댓값, 최솟값
max 메소드와 min 메소드를 사용하면 numpy array의 최댓값과 최솟값을 구할 수 있습니다.

import numpy as np

array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.max()) # 최댓값
print(array1.min()) # 최솟값
31
5
평균값
mean 메소드를 사용하면 numpy array의 평균값을 구할 수 있습니다.

import numpy as np

array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.mean()) # 평균값
15.25
위 예시에서, 총합(14+6+13+21+23+31+9+5)을 총 개수(8)로 나누면 15.25입니다.

중앙값
median 메소드를 사용하면 중간값을 구할 수 있는데요. 특이하게 median은 numpy array의 메소드가 아니라 numpy의 메소드입니다.

import numpy as np

array1 = np.array([8, 12, 9, 15, 16])
array2 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(np.median(array1)) # 중앙값
print(np.median(array2)) # 중앙값
12.0
13.5
array1을 정렬하면 중앙값이 12입니다.

array2에는 짝수개의 요소가 있기 때문에 중앙값이 13과 14 두 개입니다. 둘의 평균값을 내면 13.5입니다.

표준 편차, 분산
표준 편차와 분산은 값들이 평균에서 얼마나 떨어져 있는지 나타내는 지표입니다. 잘 모르신다면 일단 넘어가셔도 좋습니다.

import numpy as np

array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.std()) # 표준 편차
print(array1.var()) # 분산
8.496322733983215
72.1875
```